create table if not exists public."Verum Node Os" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  constraint "Verum Node Os_pkey" primary key (id)
);

create index if not exists "Verum Node Os_created_at_idx"
  on public."Verum Node Os" using btree (created_at);
